---
title: "ldsc summary"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.align='center')
```

```{r}
library(tidyverse)
require(forcats)
library(RColorBrewer)
library(pheatmap)
library(qvalue)
library(viridis)
library(dendsort)
sort_hclust <- function(...) as.hclust(dendsort(as.dendrogram(...)))
```

```{r}
dat_all <- read_tsv("res.summary.tsv", col_names = c("Cluster", "Coefficient", "Coefficient_std_error", "Coefficient_P_value", "Trait", "Set")) 
```

```{r}
results <- dat_all 
colnames(results) <- c( "Cluster", "Coefficient", "Coefficient_std_error", "Coefficient_P_value", "Trait", "Set")
```

```{r, fig.height=8, fig.width=6, cache=T}
traits <- c(
"Arvanitis.NatCommun.2019.Heart_Failure",
#"Astle.Cell.2016.Basophil_count",
#"Astle.Cell.2016.Eosinophil_count",
#"Astle.Cell.2016.Lymphocyte_count",
#"Astle.Cell.2016.Monocyte_count",
#"Astle.Cell.2016.Neutrophil_count",
"Aylward.2018.biorxiv.Type_1_Diabetes",
"Barban.NatGenet.2016.Age_First_Birth",
"Barban.NatGenet.2016.Number_Children_Born",
"Bentham.NatGenet.2015.Lupus",
"Bentham.NatGenet.2015.Systemic_lupus_erythematosus",
"Bronson.NatGenet.2016.IgA_deficiency",
"Chiou.Nature.2021.Type_1_diabetes",
"Cordell.NatCommun.2015.Primary_Biliary_Cirrhosis",
"Deary.MolPsychiatry.2017.Tiredness",
"deLange.NatGenet.2017.Crohns_Disease",
"deLange.NatGenet.2017.Inflammatory_Bowel_Disease",
"deLange.NatGenet.2017.Ulcerative_Colitis",
"Demenais.NatGenet.2018.Asthma",
"Demontis.NatGenet.2019.Attention_Deficit_Hyperactivity_Disorder",
"denHoed.NatGenet.2013.Heart_Rate",
"Dubois.NatGenet.2010.Celiacs_Disease",
#"Duncan.AmJPsychiatry.2017.Anorexia_Nervosa",
"Dupuis.NatGenet.2010.HOMA-B",
"Dupuis.NatGenet.2010.HOMA-IR",
"EAGLE.AmJMedGenet.2016.Childhood_Aggression",
"EAGLE.NatGenet.2015.Atopic_Dermatitis",
"Felix.HumMolGenet.2015.Childhood_BMI",
"Ferreira.2019.AJHG.Asthma_child_onset",
"Ferreira.NatGenet.2017.Allergy",
"GLGC.NatGenet.2013.HDL_Cholesterol",
"GLGC.NatGenet.2013.LDL_Cholesterol",
"GLGC.NatGenet.2013.Total_Cholesterol",
#"GLGC.NatGenet.2013.Triglycerides",
"Grove.NatGenet.2019.Autism_Spectrum_Disorder",
#"Hammerschlag.NatGenet.2017.Insomnia",
"Hoffmann.NatGenet.2018.HDL_cholesterol",
"Hoffmann.NatGenet.2018.LDL_cholesterol",
"Hoffmann.NatGenet.2018.Total_cholesterol",
"Hoffmann.NatGenet.2018.Triglycerides",
"Horikoshi.Nature.2016.Birth_Weight",
#"Hou.HumMolGenet.2016.Bipolar_Disorder",
#"IMSGC.NatGenet.2011.Multiple_Sclerosis",
"IMSGC.Science.2019.Multiple_sclerosis",
"Jansen.2019.NatGenet.Insomnia",
"Jansen.NatGenet.2019.Alzheimers_Disease",
"Jiang.NatGenet.2018.Vitamin_D",
"Ji.NatGenet.2017.Primary_Sclerosing_Cholangitis",
"Jin.NatGenet.2016.Autoimmune_vitiligo",
#"Jin.NatGenet.2016.Vitiligo",
"Jones.PLOSGen.2016.Chronotype",
"Jones.PLOSGen.2016.Sleep_Duration",
"Kemp.NatGenet.2017.Heel_bone_mineral_density",
"Kilpelainen.NatCommun.2016.Leptin",
#"Lambert.NatGenet.2013.Alzheimers_Disease",
#"Locke.Nature.2015.BMI",
"Luciano.NatGenet.2017.Neuroticism",
"Mahajan.NatGenet.2018.Type_2_Diabetes",
"Malik.2018.NatGenet.Stroke",
"Manning.NatGenet.2012.Fasting_Glucose",
"Manning.NatGenet.2012.Fasting_Glucose_adj_BMI",
"Manning.NatGenet.2012.Fasting_Insulin",
"Manning.NatGenet.2012.Fasting_Insulin_adj_BMI",
"Marinelli.Sleep.2016.Child_Sleep_Duration",
"Michailidou.Nature.2017.Breast_cancer",
"Namjou.BMCMed.2019.Nonalcoholic_fatty_liver_disease",
"Nelson.NatGenet.2017.Coronary_Artery_Disease",
"Nielson.2018.NatGenet.Atrial_Fibrillation",
"Okada.Nature.2014.Rheumatoid_Arthritis",
"Okbay.Nature.2016.Educational_Attainment",
"Pattaro.NatCommun.2016.Chronic_Kidney_Disease",
"PGC.MolPsychiatry.2017.Obsessive_Compulsive_Disorder",
"PGC.MolPsychiatry.2017.Post_Traumatic_Stress_Disorder",
"PGC.Nature.2014.Schizophrenia",
"ReproGen.NatGenet.2015.Age_At_Menopause",
"ReproGen.NatGenet.2017.Age_At_Menarche",
"SAIGE.UKBB.2018.Tobacco_use_disorder",
"Sakornsakolpat.NatGenet.2019.Chronic_obstructive_pulmonary_disease",
"Savage.NatGenet.2018.Intelligence",
"Saxena.NatGenet.2010.2hr_Glucose_adjBMI",
"Schafmayer.Gut.2019.Diverticular_disease",
"Schumann.PNAS.2016.Alcohol_Usage",
"Shadrina.PLoSGenet.2019.Varicose_veins",
"Shrine.NatGenet.2019.FEV1_FVC_ratio",
"Shrine.NatGenet.2019.Forced_expiration_volume",
"Shrine.NatGenet.2019.Forced_vital_capacity",
"Shrine.NatGenet.2019.Peak_expiratory_flow",
#"Sniekers.NatGenet.2017.Intelligence",
"Stahl.2018.biorxiv.Bipolar_Disorder",
"Strawbridge.Diabetes.2011.Fasting_ProInsulin",
"Taal.NatGenet.2012.Head_Circumference",
"Tachmazidou.NatGenet.2019.Osteoarthritis",
"Teumer.Diabetes.2016.Microalbuminuria",
"Teumer.NatCommun.2018.Thyroid_stimulating_hormone",
"Tin.NatGenet.2019.Gout",
"Tin.NatGenet.2019.Serum_urate",
"UKB.Neale_v2.2018.Body_mass_index",
"UKB.Neale_v2.2018.Standing_height",
"UKB.Neale_v2.2018.Vitamin_D",
"vandenBerg.BehavGenet.2016.Extraversion",
"vanderValk.HumMolGenet.2014.Birth_Length",
"vanRheenen.NatGenet.2016.Amyotrophic_Lateral_Sclerosis",
"Watanabe.NatGenet.2019.Diastolic_blood_pressure",
"Watanabe.NatGenet.2019.Pulse_rate",
"Watanabe.NatGenet.2019.Systolic_blood_pressure",
"Watson.2018.NatGenet.Anorexia_Nervosa",
"Wheeler.PlosMed.2017.HbA1c",
"Wiberg.NatCommun.2019.Carpal_tunnel_syndrome",
"Wray.biorxiv.2018.Major_Depressive_Disorder",
"Wuttke.NatGenet.2019.Blood_urea_nitrogen",
"Wuttke.NatGenet.2019.Chronic_kidney_disease",
"Wuttke.NatGenet.2019.eGFR",
"Wuttke.NatGenet.2019.Serum_creatinine",
"Yengo.biorxiv.2018.BMI",
"Yengo.biorxiv.2018.Height",
"Zhu.RespirRes.2019.Hypertension"
)

```


```{r cache=T}
cls <- results %>%
  #filter(Coefficient_P_value < 0.05 & Trait %in% traits) %>%
  filter(Trait %in% traits) %>%
  select(Cluster) %>%
  distinct() %>%
  pull()

cluster_traits <- results %>%
  filter(Trait %in% traits & Cluster %in% cls) %>%
  group_by(Trait) %>%
  mutate(FDR = p.adjust(Coefficient_P_value, method = "fdr")) %>%
  ungroup() %>%
  arrange(FDR)

mat <- results %>%
  filter(Cluster %in% cls & Trait %in% traits) %>%
  #mutate(enrich = -log10(Coefficient_P_value)) %>%
  mutate(enrich = Coefficient / Coefficient_std_error) %>%
  select(Cluster, Trait, enrich) %>%
  filter(!grepl("adj_BMI", Trait)) %>%
  spread(Trait, enrich)

rownames(mat) <- mat$Cluster
colnames(mat) <- gsub(".*[.]", "", gsub("UKBB_", "", colnames(mat)))
mat <- data.frame(mat)
mat$Cluster <- NULL

mat_p <- cluster_traits %>%
  filter(Cluster %in% cls & Trait %in% traits) %>%
  #mutate(enrich = FDR) %>%
  mutate(enrich = Coefficient_P_value) %>%
  select(Cluster, Trait, enrich) %>%
  filter(!grepl("adj_BMI", Trait)) %>%
  spread(Trait, enrich)

rownames(mat_p) <- mat_p$Cluster
colnames(mat_p) <- gsub(".*[.]", "", gsub("UKBB_", "", colnames(mat_p)))
mat_p <- data.frame(mat_p)
mat_p$Cluster <- NULL

anno <- matrix("", nrow = nrow(mat), ncol = ncol(mat))
colnames(anno) <- colnames(mat)
rownames(anno) <- rownames(mat)
#anno[mat_p<0.1] <- "-"
anno[mat_p<0.05] <- "*"
anno[mat_p<0.01] <- "**"
anno[mat_p<0.001] <- "***"

hclust_rows <- sort_hclust(hclust(dist(mat), method = "ward.D2"))
hclust_cols <- hclust(dist(t(mat)),method = "ward.D2")

pdf("multi4species.ldsc.heatmap.pdf", height = 20, width = 12)
pheatmap(mat,
         color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(60),
         breaks = seq(-2, 4, 0.1),
         #color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(30),
         #breaks = seq(0, 3, 0.1),
         fontsize_row = 8,
         fontsize_col = 8,
         display_numbers = anno,
         fontsize_number = 6,
         labels_col = gsub("_", " ", colnames(mat)),
         labels_row = rownames(mat),
#         annotation_row = row_label,
#         annotation_colors = ann_colors,
         cluster_cols = hclust_cols,
         cluster_rows = hclust_rows,
         legend = TRUE,
         legend_labels = "Enrichment",
         angle_col = 45,
         main = "Enrichment of GWAS traits in multi4species"
         #labels_row = labels[match(gsub("cluster_", "", rownames(mat)), labels$clu), ] %>% pull(name),
         )
dev.off()

write.table(mat, "multi4species.ldsc.heatmap.enrich.txt", sep="\t", col.names = T, row.names = T, quote = F)

```


# filter and sort
```{r}
mat_p.sel <- mat_p[,sapply(mat_p, min) < 0.05]

trait.sel <- colnames(mat_p.sel)
mat.sel <- mat[which(rownames(mat) %in% rownames(mat_p.sel)), which(colnames(mat) %in% colnames(mat_p.sel))]

# sort by fixed cell type
#mat.sel <- mat.sel[match(cluster.srt, rownames(mat.sel)), ]
#mat_p.sel <- mat_p.sel[match(cluster.srt, rownames(mat_p.sel)), ]


anno <- matrix("", nrow = nrow(mat.sel), ncol = ncol(mat.sel))
colnames(anno) <- colnames(mat.sel)
rownames(anno) <- rownames(mat.sel)
anno[mat_p.sel<0.05] <- "*"
anno[mat_p.sel<0.01] <- "**"
anno[mat_p.sel<0.001] <- "***"

#mat.sel <- mat.sel[cluster.srt, trait.sel]

hclust_rows <- sort_hclust(hclust(dist(mat.sel), method = "ward.D2"))
hclust_cols <- hclust(dist(t(mat.sel)),method = "ward.D2")
#mat_p.sel <- mat_p.sel[cluster.srt, trait.sel]

pdf("multi4species.ldsc.heatmap.selected.pdf", height = 20, width = 12)
pheatmap(mat.sel,
         color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(60),
         breaks = seq(-2, 4, 0.1),
         #color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(30),
         #breaks = seq(0, 3, 0.1),
         fontsize_row = 8,
         fontsize_col = 8,
         display_numbers = anno,
         fontsize_number = 6,
         labels_col = gsub("_", " ", colnames(mat.sel)),
         labels_row = rownames(mat.sel),
#         annotation_row = row_label,
#         annotation_colors = ann_colors,
#         cluster_cols = hclust_cols,
         cluster_rows = TRUE,
#         cluster_rows = hclust_rows,
         legend = TRUE,
         legend_labels = "Enrichment",
         angle_col = 90,
         main = "Enrichment of selected GWAS traits in multi4species"
         #labels_row = labels[match(gsub("cluster_", "", rownames(mat)), labels$clu), ] %>% pull(name),
         )
dev.off()

write.table(mat.sel, "multi4species.ldsc.heatmap.selected.enrich.txt", sep="\t", col.names = T, row.names = T, quote = F)

```


# check out enrichment in different group
```{r}
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("plyr"))
suppressPackageStartupMessages(library("reshape2"))
require(lattice)

# assign group
groups <- str_split_fixed(cls, "_", 2)[,2]

tmp <- str_split_fixed(groups, "_", 2)
idx <- which(tmp[,2] != "")
groups[idx] <- tmp[,2][idx]

tmp <- str_split_fixed(groups, "_", 2)
idx <- which(tmp[,2] != "")
groups[idx] <- tmp[,2][idx]

type2group <- data.frame(type=cls, group=groups)


# generate plot matrix
for(i in 1:ncol(mat)){
trait.used <- colnames(mat)[i]
#trait.used <- "Autism_Spectrum_Disorder"
enrich.used <- mat[, which(colnames(mat)==trait.used)]
data.used <- data.frame(type=rownames(mat), enrich=enrich.used)

data.used <- join(data.used, type2group, by="type")

# plot barplot
data.used.srt <- data.used[order(data.used$enrich, decreasing = T), ]
data.used.srt$type <- factor(data.used.srt$type, levels=data.used.srt$type)

pdf(paste0("plots/", trait.used, ".ldsc.enrich.pdf"), width = 12, height = 5)
p0 <- ggplot(data.used.srt, aes(x=type, y=enrich, fill=group, color=group)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
  ggtitle(trait.used)
print(p0)

# plot distribution
p1 <- ggplot(data.used, aes(x=enrich, fill=group, color=group)) +
  geom_histogram(position="identity", alpha=0.5) +
  theme_bw() +
  ggtitle(trait.used)
print(p1)

p2 <- ggplot(data.used, aes(x=enrich, fill=group, color=group)) +
  geom_density(alpha=0.5) +
  theme_bw() +
  ggtitle(trait.used)
print(p2)
dev.off()

}


#----------------
# overall
mat.long <- melt(as.matrix(mat))
colnames(mat.long) <- c("type", "trait", "enrich")
mat.long <- join(mat.long, type2group, by="type")

pdf("multi4species.ldsc.enrich.overall.density.pdf", width = 12, height = 5)
ggplot(mat.long, aes(x=enrich, fill=group, color=group)) +
  geom_density(alpha=0.5) +
  theme_bw() +
  ggtitle("Overall")
dev.off()

```


